"""Write publications.tex from the website's publication list (single source of truth).

The list lives in Nafiz43/portfolio data/publications.json, synced nightly from ORCID.
Edit data/publications.manual.json there, never publications.tex here.

Order = weighted score of freshness, first authorship, and relevance to the rest of the
resume (embedding similarity from a tiny local Ollama model; neutral if Ollama is down).
If LATEX_CMD is set, the lowest-ranked papers are dropped until the resume fits MAX_PAGES.
Run: [LATEX_CMD="pdflatex -interaction=nonstopmode 01-main.tex"] python3 tools/pubs_to_tex.py [path-or-url]
"""
import datetime
import html
import json
import math
import os
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

SRC = "https://raw.githubusercontent.com/Nafiz43/portfolio/main/data/publications.json"
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "publications.tex"
OLLAMA = os.environ.get("OLLAMA_HOST", "http://localhost:11434")
MODEL = os.environ.get("OLLAMA_MODEL", "all-minilm")  # 23M-param sentence embedder
MAX_PAGES = int(os.environ.get("MAX_PAGES", "2"))
W_FRESH, W_FIRST, W_REL = 0.4, 0.3, 0.3


def load(src):
    if src.startswith("http"):
        with urllib.request.urlopen(src, timeout=30) as r:
            return json.load(r)
    return json.loads(Path(src).read_text())


def tex(s):
    """HTML snippet from the JSON -> LaTeX-safe text (keeps <b> as bold)."""
    s = re.sub(r"<b>(.*?)</b>", "\x00\\1\x01", s or "")
    s = html.unescape(re.sub(r"<[^>]+>", "", s))
    s = re.sub(r"([&%$#_{}])", r"\\\1", s).replace("~", r"\textasciitilde{}").replace("^", r"\^{}")
    return s.replace("\x00", r"\textbf{").replace("\x01", "}")


def item(p):
    parts = [tex(p["authors"]) + "," if p.get("authors") else "", f"``{tex(p['title'])},''"]
    if p.get("venue"):
        parts.append(tex(p["venue"]) + ",")
    parts.append("(Under review)." if p["year"] == "TBD" else f"{p['year']}.")
    if p.get("award"):
        parts.append(rf"\textbf{{({tex(p['award'])})}}")
    if p.get("resume_note"):
        parts.append(rf"\textbf{{({tex(p['resume_note'])})}}")
    if p.get("link"):
        parts.append(rf"[\href{{{p['link'].replace('%', r'\%').replace('#', r'\#')}}}{{\underline{{LINK}}}}]")
    return "    \\item " + " ".join(x for x in parts if x)


def resume_focus():
    """The resume's Summary section (its distilled research focus), LaTeX stripped."""
    s = (ROOT / "01-main.tex").read_text().split(r"\section{Summary}")[1].split(r"\section")[0]
    return re.sub(r"\s+", " ", re.sub(r"(?<!\\)%.*", "", s)).strip()


def relevance(pubs):
    """0..1 per paper: embedding cosine of title vs resume focus, min-max scaled.
    Neutral 0.5 if Ollama is unreachable so the build never breaks."""
    try:
        body = json.dumps({"model": MODEL, "input": [resume_focus()] + [p["title"] for p in pubs]}).encode()
        with urllib.request.urlopen(urllib.request.Request(f"{OLLAMA}/api/embed", body), timeout=300) as r:
            q, *docs = json.load(r)["embeddings"]
    except Exception as e:
        print(f"relevance fallback (all 0.5): {e}", file=sys.stderr)
        return [0.5] * len(pubs)
    cos = [sum(x * y for x, y in zip(q, d)) / math.sqrt(sum(x * x for x in q) * sum(y * y for y in d)) for d in docs]
    lo, hi = min(cos), max(cos)
    return [(c - lo) / (hi - lo or 1) for c in cos]


def first_author(p):
    """First listed, or marked equal-contribution (*)."""
    a = p.get("authors") or ""
    return a.startswith("<b>") or bool(re.search(r"</b>\*", a))


def score(p, rel, year=datetime.date.today().year):
    # ponytail: under-review (TBD) papers get half freshness; tune if they should rank higher.
    fresh = max(0.0, 1 - (year - int(p["year"])) / 6) if p["year"].isdigit() else 0.5
    return W_FRESH * fresh + W_FIRST * first_author(p) + W_REL * rel


def rank(pubs):
    scored = [(score(p, rel), p) for p, rel in zip(pubs, relevance(pubs))]
    scored.sort(key=lambda t: t[0], reverse=True)
    for sc, p in scored:
        print(f"{sc:.2f}  {p['year']:>4}  {p['title'][:70]}")
    return [p for _, p in scored]


def pages():
    subprocess.run(os.environ["LATEX_CMD"], shell=True, cwd=ROOT, capture_output=True)
    # \pagenumbering{gobble} blanks lastpage's label, so read pdflatex's own count from the log.
    return int(re.search(r"Output written on .*?\((\d+) pages?", (ROOT / "01-main.log").read_text(errors="ignore")).group(1))


def fit(pubs):
    """Largest prefix of the ranked list that keeps the resume within MAX_PAGES (binary search)."""
    lo, hi = 0, len(pubs)
    while lo < hi:
        mid = (lo + hi + 1) // 2
        OUT.write_text(render(pubs[:mid]))
        lo, hi = (mid, hi) if pages() <= MAX_PAGES else (lo, mid - 1)
    for p in pubs[lo:]:
        print(f"dropped to fit {MAX_PAGES} pages: {p['title'][:70]}")
    return pubs[:lo]


def render(pubs):
    body = "\n\n".join(item(p) for p in pubs)
    return "% AUTO-GENERATED by tools/pubs_to_tex.py from Nafiz43/portfolio data/publications.json. Do not edit.\n" \
           f"\\begin{{enumerate}}\n{body}\n\\end{{enumerate}}\n"


def demo():
    out = item({"authors": "A*, <b>N K</b>*", "title": "Q&A 100%", "venue": "SEET", "year": "2025", "award": "Best Paper Award", "link": "https://x.org/a%20b"})
    assert r"\textbf{N K}" in out and r"Q\&A 100\%" in out and r"\textbf{(Best Paper Award)}" in out and r"a\%20b" in out, out
    assert first_author({"authors": "<b>N K</b>, B"}) and first_author({"authors": "A*, <b>N K</b>*"})
    assert not first_author({"authors": "A, <b>N K</b>"})
    assert score({"authors": "<b>N</b>", "year": "2026"}, 1, 2026) > score({"authors": "A, <b>N</b>", "year": "2020"}, 1, 2026)


if __name__ == "__main__":
    demo()
    pubs = load(sys.argv[1] if len(sys.argv) > 1 else SRC)
    pubs = rank(pubs)
    if os.environ.get("LATEX_CMD"):
        pubs = fit(pubs)
    OUT.write_text(render(pubs))
    print(f"wrote {OUT.name}: {len(pubs)} publications")
