"""Write publications.tex from the website's publication list (single source of truth).

The list lives in Nafiz43/portfolio data/publications.json, synced nightly from ORCID.
Edit data/publications.manual.json there, never publications.tex here.
Run: python3 tools/pubs_to_tex.py [path-or-url]
"""
import html
import json
import re
import sys
import urllib.request
from pathlib import Path

SRC = "https://raw.githubusercontent.com/Nafiz43/portfolio/main/data/publications.json"
OUT = Path(__file__).resolve().parent.parent / "publications.tex"


def load(src):
    if src.startswith("http"):
        with urllib.request.urlopen(src, timeout=30) as r:
            return json.load(r)
    return json.loads(Path(src).read_text())


def tex(s):
    """HTML snippet from the JSON -> LaTeX-safe text (keeps <b> as bold)."""
    s = re.sub(r"<b>(.*?)</b>", "\x00\\1\x01", s or "")
    s = html.unescape(re.sub(r"<[^>]+>", "", s))
    s = re.sub(r"([&%$#_{}])", r"\\\1", s).replace("~", r"\textasciitilde{}").replace("^", r"\^{}")
    return s.replace("\x00", r"\textbf{").replace("\x01", "}")


def item(p):
    parts = [tex(p["authors"]) + "," if p.get("authors") else "", f"``{tex(p['title'])},''"]
    if p.get("venue"):
        parts.append(tex(p["venue"]) + ",")
    parts.append("(Under review)." if p["year"] == "TBD" else f"{p['year']}.")
    if p.get("award"):
        parts.append(rf"\textbf{{({tex(p['award'])})}}")
    if p.get("resume_note"):
        parts.append(rf"\textbf{{({tex(p['resume_note'])})}}")
    if p.get("link"):
        parts.append(rf"[\href{{{p['link'].replace('%', r'\%').replace('#', r'\#')}}}{{\underline{{LINK}}}}]")
    return "    \\item " + " ".join(x for x in parts if x)


def render(pubs):
    # Resume order: newest first, under-review work last.
    pubs = sorted(pubs, key=lambda p: p["year"] if p["year"].isdigit() else "0000", reverse=True)
    body = "\n\n".join(item(p) for p in pubs)
    return "% AUTO-GENERATED by tools/pubs_to_tex.py from Nafiz43/portfolio data/publications.json. Do not edit.\n" \
           f"\\begin{{enumerate}}\n{body}\n\\end{{enumerate}}\n"


def demo():
    out = item({"authors": "A*, <b>N K</b>*", "title": "Q&A 100%", "venue": "SEET", "year": "2025", "award": "Best Paper Award", "link": "https://x.org/a%20b"})
    assert r"\textbf{N K}" in out and r"Q\&A 100\%" in out and r"\textbf{(Best Paper Award)}" in out and r"a\%20b" in out, out
    assert render([{"authors": "", "title": "a", "year": "TBD"}, {"authors": "", "title": "b", "year": "2020"}]).index("``b") < \
        render([{"authors": "", "title": "a", "year": "TBD"}, {"authors": "", "title": "b", "year": "2020"}]).index("``a")


if __name__ == "__main__":
    demo()
    pubs = load(sys.argv[1] if len(sys.argv) > 1 else SRC)
    OUT.write_text(render(pubs))
    print(f"wrote {OUT.name}: {len(pubs)} publications")
